### ISSUE TITLE
No module named 'aiohttp.wsgi'

### ISSUE THREAD

**Issue by fojetin** [Hardtack/Flask-aiohttp#9]
```
    from aiohttp.wsgi import WSGIServerHttpProtocol
ModuleNotFoundError: No module named 'aiohttp.wsgi'

```
i just install Flask-aiohttp with `pip install git+https://github.com/Hardtack/Flask-aiohttp.git#egg=Flask-aiohttp`

full code it's just this:
```
from flask import Flask
from flask.ext.aiohttp import async
```

**Comment by hardtack** [comment]
It causes because of dependency for old version of aiohttp. 
I’m sorry but i’m not intended to maintain this project since it was just an experimental project and too old.
Thank you for reporting 🙏
